version : '3'

networks:
  default:
    driver: bridge

services :

  testeplbackend-api :
    build:
      context: ./testeplbackend-api
      dockerfile: Dockerfile.dev
    container_name: testeplbackend-api
    restart: always
    volumes:
      - ./testeplbackend-api:/src/apiToDo
    ports:
      - "5171:8080"
      - "5170:8181" 

  testeplfrontend-ui :
    build:
      context: ./testeplfrontend-ui
      dockerfile: Dockerfile.dev
    container_name: testeplfrontend-ui
    restart: always
    volumes:
      - ./testeplfrontend-ui/:/usr/src/workspace/testeplfrontend-ui
    ports:
      - 5172:5172