version : '3'

networks:
  default:
    driver: bridge

services :

  testeplfrontend-ui :
    build:
      context: ./testeplfrontend-ui
      dockerfile: Dockerfile.dev
    container_name: testeplfrontend-ui
    restart: always
    volumes:
      - ./testeplfrontend-ui/:/usr/src/workspace/testeplfrontend-ui
    ports:
      - 5172:5172